import { Injectable, inject, signal } from '@angular/core';
import { Subscription, interval } from 'rxjs';
import { Api } from './api';

const STORAGE_KEY = 'discoveryhub.demo-disposition';

/** How often the archive is asked whether the demo message has landed. */
const POLL_MS = 2000;

/**
 * How long to wait for the demo message to be archived. Ingestion answers 202
 * before anything is stored, so the message only exists once Kafka has carried
 * it to archive-service; a minute is generous for one message, and past it
 * something in the pipeline is down.
 */
const ARCHIVE_TIMEOUT_MS = 60_000;

/** Where a demo disposition has got to. */
export type DemoStage =
  | 'INGESTING'
  | 'WAITING'
  | 'DELETING'
  | 'DELETED'
  | 'HELD'
  | 'FAILED';

/** Stages where work is still outstanding, and so worth resuming. */
const ACTIVE_STAGES: DemoStage[] = ['INGESTING', 'WAITING', 'DELETING'];

/** One throwaway message, watched from ingestion through to its deletion. */
export interface DemoDisposition {
  sourceMessageId: string;
  type: 'EMAIL' | 'CHAT';
  retentionMinutes: number;
  stage: DemoStage;
  /** The archive's own id, known only once the message has been stored. */
  messageId?: string;
  /** Epoch millis at which the message passes its retention cut-off. */
  deleteAt?: number;
  /** Epoch millis the demo was started, to bound the wait for archival. */
  startedAt: number;
  detail?: string;
}

/**
 * The demo disposition (FR-5.2, shown small).
 *
 * <p>A real disposition run acts on the whole corpus, so on a demo-length
 * retention policy it empties the archive — true to the requirement, but not
 * something you can show twice. This does the same thing to exactly one
 * message: generate it, wait out the retention period its type's policy sets,
 * then delete that message and nothing else. It is not a simulation — the
 * message is really ingested, really archived, and really deleted through the
 * same endpoint the disposition job calls, so a legal hold covering it still
 * blocks the deletion with 409 (FR-4.6).
 *
 * <p><b>Why this is a root service and not part of the retention screen.</b>
 * Every route is a lazy `loadComponent`, so navigating to another tab destroys
 * the component and everything scoped to it. When the countdown lived there,
 * leaving the page silently cancelled the deletion and the demo only worked if
 * you stared at one screen for the whole retention period — which is precisely
 * what you cannot do while presenting. The wait belongs to the application, so
 * it lives for as long as the application does.
 *
 * <p>A full page reload does end the application, so the outstanding demo is
 * mirrored to localStorage and picked back up on startup. Persistence covers
 * the active stages only; a finished result is in-memory news, not state worth
 * restoring.
 */
@Injectable({ providedIn: 'root' })
export class DemoDispositionService {
  private readonly api = inject(Api);

  readonly state = signal<DemoDisposition | null>(null);
  readonly remainingSeconds = signal(0);

  private timer?: Subscription;

  constructor() {
    this.resume();
  }

  /** True while the demo is mid-flight and a second one would collide. */
  running(): boolean {
    const stage = this.state()?.stage;
    return stage !== undefined && ACTIVE_STAGES.includes(stage);
  }

  /**
   * Generates one message and starts the clock on it.
   *
   * @param retentionMinutes the period configured for this type, which is what
   *                         makes the demo a demonstration of the policy
   *                         rather than of an arbitrary delay
   */
  start(type: 'EMAIL' | 'CHAT', retentionMinutes: number): void {
    this.cancel();

    const sourceMessageId = `demo-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
    const sentAt = Date.now();
    this.write({
      sourceMessageId,
      type,
      retentionMinutes,
      stage: 'INGESTING',
      startedAt: sentAt,
      deleteAt: sentAt + retentionMinutes * 60_000,
    });

    this.api
      .ingestMessage({
        sourceMessageId,
        type,
        subject: `Demo disposition message (${sourceMessageId})`,
        body:
          'Generated by the demo disposition. It exists only to be deleted ' +
          `once the ${type} retention period of ${retentionMinutes} ` +
          'minute(s) has elapsed.',
        timestamp: new Date(sentAt).toISOString(),
        sender: 'demo@smarsh.com',
        participants: ['demo@smarsh.com'],
      })
      .subscribe({
        next: () => this.awaitArchival(),
        error: (e) => this.fail(messageOf(e)),
      });
  }

  /**
   * Abandons the demo. The message itself is left in the archive: deleting it
   * out of band would be a deletion the disposition record never mentions, and
   * the next real run will dispose of it anyway.
   */
  cancel(): void {
    this.timer?.unsubscribe();
    this.timer = undefined;
    this.remainingSeconds.set(0);
    this.state.set(null);
    clearStored();
  }

  /**
   * Ingestion answers 202 before the message exists anywhere, and the delete
   * needs the archive's own id, not the source id we chose. So poll the
   * archive until it can name the message — a 404 here means "not yet".
   */
  private awaitArchival(): void {
    this.timer?.unsubscribe();
    this.timer = interval(POLL_MS).subscribe(() => {
      const current = this.state();
      if (!current) return;
      this.api.getMessageBySource(current.sourceMessageId).subscribe({
        next: (message) => {
          this.timer?.unsubscribe();
          this.write({
            ...current,
            stage: 'WAITING',
            messageId: message.id,
          });
          this.countDownToDeletion();
        },
        error: () => {
          if (Date.now() - current.startedAt > ARCHIVE_TIMEOUT_MS) {
            this.timer?.unsubscribe();
            this.fail(
              'The demo message was accepted but never archived. Ingestion ' +
                'is asynchronous, so check that Kafka and archive-service ' +
                'are up.',
            );
          }
        },
      });
    });
  }

  /** Ticks down the retention period, then disposes of the message. */
  private countDownToDeletion(): void {
    this.timer?.unsubscribe();
    const tick = () => {
      const deleteAt = this.state()?.deleteAt ?? 0;
      const remaining = Math.max(0, Math.ceil((deleteAt - Date.now()) / 1000));
      this.remainingSeconds.set(remaining);
      if (remaining === 0) {
        this.timer?.unsubscribe();
        this.deleteMessage();
      }
    };
    tick();
    // The cut-off may already have passed — after a reload, for instance —
    // in which case the deletion has happened and there is nothing to time.
    if (this.remainingSeconds() === 0) return;
    this.timer = interval(1000).subscribe(tick);
  }

  private deleteMessage(): void {
    const current = this.state();
    if (!current?.messageId) return;
    this.write({ ...current, stage: 'DELETING' });

    this.api.deleteMessage(current.messageId, 'demo-disposition').subscribe({
      next: () => {
        this.write({ ...current, stage: 'DELETED' });
        this.confirmGone(current.sourceMessageId);
      },
      error: (e) => {
        const status = (e as { status?: number })?.status;
        // 409 is not a failure: it is the legal-hold guarantee doing its job.
        if (status === 409) {
          this.write({
            ...current,
            stage: 'HELD',
            detail:
              'Deletion was refused with 409 because a legal hold covers this ' +
              'message — the same refusal a real disposition run records as ' +
              'preserved (FR-4.6).',
          });
          return;
        }
        // Resuming after a reload can re-issue a delete that already
        // succeeded. The message being gone is the outcome we wanted.
        if (status === 404) {
          this.write({
            ...current,
            stage: 'DELETED',
            detail: 'The archive no longer holds this message.',
          });
          return;
        }
        this.fail(messageOf(e));
      },
    });
  }

  /**
   * Reads back the message that was just deleted. "The archive no longer knows
   * this id" is the part of the demo worth showing; a 200 from the delete call
   * only says the request was accepted.
   */
  private confirmGone(sourceMessageId: string): void {
    this.api.getMessageBySource(sourceMessageId).subscribe({
      next: () =>
        this.detail(
          'Deleted, but the archive still returns the message — refresh in a ' +
            'moment, and check archive-service if it persists.',
        ),
      error: (e) =>
        this.detail(
          (e as { status?: number })?.status === 404
            ? 'Confirmed: the archive no longer holds this message.'
            : 'Deleted. The archive could not be re-read to confirm it.',
        ),
    });
  }

  private detail(detail: string): void {
    const current = this.state();
    if (current) this.write({ ...current, detail });
  }

  private fail(detail: string): void {
    this.timer?.unsubscribe();
    const current = this.state();
    if (current) this.write({ ...current, stage: 'FAILED', detail });
  }

  /** Single point of change, so the mirror can never drift from the state. */
  private write(next: DemoDisposition): void {
    this.state.set(next);
    if (ACTIVE_STAGES.includes(next.stage)) {
      writeStored(next);
    } else {
      clearStored();
    }
  }

  /**
   * Picks a demo back up after a reload. Whatever stage it was in, the work
   * left to do is a function of the stored state alone — which is why the
   * archive id and the cut-off are persisted rather than recomputed.
   */
  private resume(): void {
    const stored = readStored();
    if (!stored) return;
    this.state.set(stored);
    if (stored.stage === 'INGESTING') {
      this.awaitArchival();
    } else if (stored.stage === 'WAITING') {
      this.countDownToDeletion();
    } else {
      this.deleteMessage();
    }
  }
}

function messageOf(error: unknown): string {
  const e = error as { error?: { message?: string }; message?: string };
  return e?.error?.message ?? e?.message ?? 'Request failed';
}

/**
 * localStorage is guarded exactly as in ActorService: it is unavailable in
 * private browsing, under server-side rendering and in a bare test
 * environment, and an exception here would break the demo rather than merely
 * fail to persist it. The in-memory signal is the source of truth.
 */
function readStored(): DemoDisposition | null {
  try {
    const raw = globalThis.localStorage?.getItem(STORAGE_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw) as DemoDisposition;
    return ACTIVE_STAGES.includes(parsed?.stage) ? parsed : null;
  } catch {
    return null;
  }
}

function writeStored(state: DemoDisposition): void {
  try {
    globalThis.localStorage?.setItem(STORAGE_KEY, JSON.stringify(state));
  } catch {
    // Persistence is best-effort; the demo still works within this page load.
  }
}

function clearStored(): void {
  try {
    globalThis.localStorage?.removeItem(STORAGE_KEY);
  } catch {
    // As above.
  }
}
